import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getFirestore, collection, doc, getDocs, getDoc, setDoc, addDoc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

let staff = [], training = [], sessions = [], rules = {}, activeSession = null, scanner = null;
let trainingFilter = "all";
const WARNING_DAYS = 90, NO_EXPIRY = "NO_EXPIRY";

Object.assign(window,{reloadAll,seedRules,saveStaff,clearStaffForm,renderStaff,lookupStaff,saveTraining,clearTrainingForm,renderTraining,setTrainingFilter,applyRuleToTraining,toggleTrainingNoExpiry,applyRuleToSession,toggleSessionNoExpiry,createSession,addManualAttendance,finalizeSession,clearAttendance,startScanner,stopScanner,renderCertRecords,uploadIndividualEvidence,uploadSessionEvidence,saveRule,deleteRule,toggleRuleYears,closeViewer,editStaff,deleteStaff,editTraining,deleteTraining,viewUrl,viewSessionEvidence,renderReports,exportTrainingCSV});

document.addEventListener("DOMContentLoaded", async () => {
  document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.tab,b)));
  await reloadAll();
});

function openTab(id,btn){document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.querySelectorAll(".tabs button").forEach(b=>b.classList.remove("active"));document.getElementById(id).classList.add("active");btn.classList.add("active");if(id==="cards")renderQrCards();if(id==="certs")renderCerts();if(id==="reports")renderReports("expired");}
async function reloadAll(){try{staff=await loadCollection("staff");training=await loadCollection("training");sessions=await loadCollection("sessions");const rr=await loadCollection("rules");rules={};rr.forEach(r=>rules[r.id]=r);const a=await getDoc(doc(db,"system","activeSession"));activeSession=a.exists()&&a.data().course?a.data():null;renderAll();}catch(e){console.error(e);alert("Firebase loading failed. Check firebase-config.js and Firestore rules. "+e.message);}}
async function loadCollection(name){const snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,...d.data()}));}
function renderAll(){renderMetrics();renderStaff();renderTraining();renderRules();renderCourseOptions();renderActiveSession();renderAttendance();renderCerts();renderQrCards();}
function staffById(id){return staff.find(s=>s.id.toUpperCase()===String(id||"").toUpperCase());}
function trainingsByStaff(id){return training.filter(t=>t.staffId.toUpperCase()===String(id||"").toUpperCase()).sort((a,b)=>String(a.expiry).localeCompare(String(b.expiry)));}
function upper(v){return String(v||"").trim().toUpperCase();}
function splitCsv(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean);}
function fmt(d){if(!d||d===NO_EXPIRY)return"N.A. (No expiry)";return new Date(d+"T00:00:00").toLocaleDateString("en-SG",{day:"2-digit",month:"short",year:"numeric"});}
function daysUntil(d){const today=new Date();today.setHours(0,0,0,0);return Math.ceil((new Date(d+"T00:00:00")-today)/86400000);}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function addYears(dateStr,years){const d=new Date(dateStr+"T00:00:00");d.setMonth(d.getMonth()+Math.round(Number(years)*12));d.setDate(d.getDate()-1);return d.toISOString().slice(0,10);}
function isNoExpiryRecord(t){return t.noExpiry===true||t.expiry===NO_EXPIRY;}
function statusOf(t){if(isNoExpiryRecord(t))return{label:"Valid – No Expiry",cls:"noexpiry",days:null};if(!t.expiry)return{label:"Expiry Missing",cls:"expired",days:null};const days=daysUntil(t.expiry);if(days<0)return{label:"Expired",cls:"expired",days};if(days<=WARNING_DAYS)return{label:"Expiring Soon",cls:"expiring",days};return{label:"Valid",cls:"valid",days};}
function initialsAvatar(name){const i=String(name||"Staff").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join("")||"ST";return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="120" height="120" rx="60" fill="#e2e8f0"/><text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="40" font-weight="700" fill="#334155">${i}</text></svg>`)}`;}
function ruleForCourse(course){return rules[course];}
function isRuleNoExpiry(course){const r=ruleForCourse(course);return r&&(r.type==="noexpiry"||Number(r.years)===0);}

async function saveStaff(){const id=upper(document.getElementById("staffId").value),name=document.getElementById("staffName").value.trim();if(!id||!name)return alert("Staff ID and name required.");await setDoc(doc(db,"staff",id),{id,name,company:document.getElementById("staffCompany").value.trim()||"N.A.",trade:document.getElementById("staffTrade").value.trim()||"N.A.",dept:document.getElementById("staffDept").value.trim()||"N.A.",status:document.getElementById("staffStatus").value,photoUrl:document.getElementById("staffPhotoUrl").value.trim()||"",updatedAt:serverTimestamp()});clearStaffForm();await reloadAll();alert("Staff saved.");}
function clearStaffForm(){["staffId","staffName","staffTrade","staffDept","staffPhotoUrl"].forEach(id=>document.getElementById(id).value="");document.getElementById("staffCompany").value="Bryan Boiler Engineering Pte Ltd";document.getElementById("staffStatus").value="Active";document.getElementById("staffId").disabled=false;}
function editStaff(id){const s=staffById(id);if(!s)return;openTab("staff",document.querySelector('[data-tab="staff"]'));document.getElementById("staffId").value=s.id;document.getElementById("staffId").disabled=true;document.getElementById("staffName").value=s.name;document.getElementById("staffCompany").value=s.company||"";document.getElementById("staffTrade").value=s.trade||"";document.getElementById("staffDept").value=s.dept||"";document.getElementById("staffStatus").value=s.status||"Active";document.getElementById("staffPhotoUrl").value=s.photoUrl||"";}
async function deleteStaff(id){if(!confirm("Delete staff? Training records will remain unless manually removed."))return;await deleteDoc(doc(db,"staff",id));await reloadAll();}
function renderStaff(){const q=(document.getElementById("staffSearch")?.value||"").toLowerCase();document.getElementById("staffList").innerHTML=staff.filter(s=>`${s.id} ${s.name} ${s.trade} ${s.dept}`.toLowerCase().includes(q)).map(s=>{const blocked=s.status!=="Active"||trainingsByStaff(s.id).some(t=>statusOf(t).label==="Expired");return`<div class="rowCard staffRow"><img class="avatarSmall" src="${s.photoUrl||initialsAvatar(s.name)}"><div><b>${esc(s.name)}</b><br><span class="small">${esc(s.id)} · ${esc(s.trade)} · ${esc(s.dept)}</span><br><span class="badge ${blocked?'expired':'valid'}">${blocked?'Blocked':'Clear'}</span></div><div><button onclick="setLookup('${s.id}')">Lookup</button><button onclick="editStaff('${s.id}')">Edit</button><button class="danger" onclick="deleteStaff('${s.id}')">Delete</button></div></div>`}).join("")||"<p>No staff found.</p>";}
window.setLookup=function(id){document.getElementById("lookupId").value=id;openTab("lookup",document.querySelector('[data-tab="lookup"]'));lookupStaff();}
function lookupStaff(){const id=upper(document.getElementById("lookupId").value),s=staffById(id),out=document.getElementById("lookupResult");if(!s){out.innerHTML=`<div class="banner block">Staff ID not found</div>`;return;}const recs=trainingsByStaff(id),expired=recs.filter(r=>statusOf(r).label==="Expired"),blocked=s.status!=="Active"||expired.length>0,active=recs.filter(r=>statusOf(r).label!=="Expired"),machines=[...new Set(active.flatMap(r=>r.machines||[]))],highRisk=[...new Set(active.flatMap(r=>r.highRisk||[]))];out.innerHTML=`<div class="banner ${blocked?'block':'clear'}">${blocked?'DO NOT DEPLOY':'CLEARED FOR DEPLOYMENT'}</div><div class="profile"><div class="panel"><img class="avatar" src="${s.photoUrl||initialsAvatar(s.name)}"><h3>${esc(s.name)}</h3><p><strong>${esc(s.id)}</strong></p><p>${esc(s.trade)}</p><p class="small">${esc(s.company)} · ${esc(s.dept)}</p></div><div><div class="panel"><b>Machines:</b> ${machines.map(x=>`<span class="badge neutral">${esc(x)}</span>`).join(" ")||"None"}<br><b>High Risk:</b> ${highRisk.map(x=>`<span class="badge neutral">${esc(x)}</span>`).join(" ")||"None"}</div>${recs.map(trainingCard).join("")||"<div class='record'>No training records.</div>"}</div></div>`;}

function applyRuleToTraining(){const course=document.getElementById("trCourse").value.trim(),attended=document.getElementById("trAttended").value,expiry=document.getElementById("trExpiry"),noExp=document.getElementById("trNoExpiry"),hint=document.getElementById("trRuleHint"),r=ruleForCourse(course);if(r){hint.textContent=r.type==="noexpiry"?`Rule: No expiry. ${r.note||""}`:`Rule: Valid for ${r.years} year(s). ${r.note||""}`;if(r.type==="noexpiry"||Number(r.years)===0){noExp.checked=true;toggleTrainingNoExpiry();return;}if(attended&&!expiry.value)expiry.value=addYears(attended,r.years);}else hint.textContent="No rule found. Select no expiry manually or enter expiry date.";}
function toggleTrainingNoExpiry(){const checked=document.getElementById("trNoExpiry").checked,expiry=document.getElementById("trExpiry");expiry.disabled=checked;if(checked)expiry.value="";}
async function saveTraining(){const id=document.getElementById("trainingDocId").value,staffId=upper(document.getElementById("trStaffId").value),course=document.getElementById("trCourse").value.trim(),attended=document.getElementById("trAttended").value,noExpiry=document.getElementById("trNoExpiry").checked||isRuleNoExpiry(course);let expiry=document.getElementById("trExpiry").value;if(!staffById(staffId))return alert("Staff ID not found.");if(!course||!attended)return alert("Course and attended date required.");if(noExpiry)expiry=NO_EXPIRY;else if(!expiry&&rules[course])expiry=addYears(attended,rules[course].years);if(!noExpiry&&!expiry)return alert("Expiry required, unless No Expiry is selected.");const data={staffId,course,provider:document.getElementById("trProvider").value.trim()||"N.A.",certNo:document.getElementById("trCertNo").value.trim()||"N.A.",attended,expiry,noExpiry,machines:splitCsv(document.getElementById("trMachines").value),highRisk:splitCsv(document.getElementById("trHighRisk").value),certLink:document.getElementById("trCertLink").value.trim()||"",cardLink:document.getElementById("trCardLink").value.trim()||"",remarks:document.getElementById("trRemarks").value.trim()||"N.A.",updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,"training",id),data);else await addDoc(collection(db,"training"),{...data,createdAt:serverTimestamp()});clearTrainingForm();await reloadAll();alert("Training saved.");}
function clearTrainingForm(){["trainingDocId","trStaffId","trCourse","trProvider","trCertNo","trAttended","trExpiry","trMachines","trHighRisk","trCertLink","trCardLink","trRemarks"].forEach(id=>document.getElementById(id).value="");document.getElementById("trNoExpiry").checked=false;document.getElementById("trExpiry").disabled=false;document.getElementById("trRuleHint").textContent="";}
function editTraining(id){const t=training.find(x=>x.id===id);if(!t)return;openTab("training",document.querySelector('[data-tab="training"]'));document.getElementById("trainingDocId").value=t.id;document.getElementById("trStaffId").value=t.staffId;document.getElementById("trCourse").value=t.course;document.getElementById("trProvider").value=t.provider;document.getElementById("trCertNo").value=t.certNo;document.getElementById("trAttended").value=t.attended;document.getElementById("trNoExpiry").checked=isNoExpiryRecord(t);document.getElementById("trExpiry").value=isNoExpiryRecord(t)?"":(t.expiry||"");document.getElementById("trMachines").value=(t.machines||[]).join(", ");document.getElementById("trHighRisk").value=(t.highRisk||[]).join(", ");document.getElementById("trCertLink").value=t.certLink||t.cert?.url||"";document.getElementById("trCardLink").value=t.cardLink||t.card?.url||"";document.getElementById("trRemarks").value=t.remarks||"";toggleTrainingNoExpiry();}
async function deleteTraining(id){if(!confirm("Delete training record?"))return;await deleteDoc(doc(db,"training",id));await reloadAll();}
function setTrainingFilter(type){trainingFilter=type;renderTraining();}
function filterTrainingRows(rows){return rows.filter(t=>{const st=statusOf(t);if(trainingFilter==="expired")return st.label==="Expired";if(trainingFilter==="expiring")return st.label==="Expiring Soon";if(trainingFilter==="noexpiry")return isNoExpiryRecord(t);if(trainingFilter==="missingEvidence")return !getCertUrl(t)&&!getSessionEvidenceUrl(t);return true;});}
function renderTraining(){const q=(document.getElementById("trainingSearch")?.value||"").toLowerCase();let rows=training.filter(t=>`${t.staffId} ${staffById(t.staffId)?.name||""} ${t.course} ${t.certNo} ${t.remarks||""}`.toLowerCase().includes(q));rows=filterTrainingRows(rows);document.getElementById("trainingTable").innerHTML=rows.map(t=>{const s=staffById(t.staffId),st=statusOf(t);return`<tr><td>${esc(s?.name||"Unknown")}<br><span class="small">${esc(t.staffId)}</span></td><td>${esc(t.course)}<br><span class="small">${esc(t.provider)} · ${esc(t.certNo)}</span></td><td><span class="badge ${st.cls}">${st.label}</span><br><span class="small">${isNoExpiryRecord(t)?"No periodic renewal required":fmt(t.expiry)+" · "+st.days+" days"}</span></td><td>${evidenceButtons(t)}</td><td><button onclick="editTraining('${t.id}')">Edit</button><button class="danger" onclick="deleteTraining('${t.id}')">Delete</button></td></tr>`}).join("")||"<tr><td colspan='5'>No records.</td></tr>";}
function getCertUrl(t){return t.certLink||t.cert?.url||"";}function getCardUrl(t){return t.cardLink||t.card?.url||"";}function getSessionEvidenceUrl(t){return t.sessionEvidenceLink||t.sessionEvidenceUrl||"";}
function evidenceButtons(t){const cert=getCertUrl(t),card=getCardUrl(t),session=getSessionEvidenceUrl(t);return`${cert?`<button onclick="viewUrl('${esc(cert)}','${esc(t.course)} Certificate')">Cert</button>`:"No cert"} ${card?`<button onclick="viewUrl('${esc(card)}','${esc(t.course)} Card')">Card</button>`:""} ${session?`<button onclick="viewUrl('${esc(session)}','Session Evidence')">Session Evidence</button>`:""}`;}
function trainingCard(t){const st=statusOf(t);return`<div class="record"><h3>${esc(t.course)} <span class="badge ${st.cls}">${st.label}</span></h3><p class="small">Provider: ${esc(t.provider)} · Cert/Record No: ${esc(t.certNo)}<br>Attended: ${fmt(t.attended)} · Expiry: ${fmt(t.expiry)} ${isNoExpiryRecord(t)?"":"· "+(st.days<0?Math.abs(st.days)+" days overdue":st.days+" days remaining")}</p><p>${esc(t.remarks)}</p><div>${evidenceButtons(t)}</div></div>`;}

function applyRuleToSession(){const course=document.getElementById("sessCourse").value.trim(),date=document.getElementById("sessDate").value,expiry=document.getElementById("sessExpiry"),noExp=document.getElementById("sessNoExpiry"),hint=document.getElementById("sessRuleHint"),r=ruleForCourse(course);if(r){hint.textContent=r.type==="noexpiry"?`Rule: No expiry. ${r.note||""}`:`Rule: Valid for ${r.years} year(s). ${r.note||""}`;if(r.type==="noexpiry"||Number(r.years)===0){noExp.checked=true;toggleSessionNoExpiry();return;}if(date&&!expiry.value)expiry.value=addYears(date,r.years);}else hint.textContent="No rule found. Select no expiry manually or enter expiry date.";}
function toggleSessionNoExpiry(){const checked=document.getElementById("sessNoExpiry").checked,expiry=document.getElementById("sessExpiry");expiry.disabled=checked;if(checked)expiry.value="";}
async function createSession(){const course=document.getElementById("sessCourse").value.trim(),date=document.getElementById("sessDate").value,noExpiry=document.getElementById("sessNoExpiry").checked||isRuleNoExpiry(course);let expiry=document.getElementById("sessExpiry").value;if(!course||!date)return alert("Course and date required.");if(noExpiry)expiry=NO_EXPIRY;else if(!expiry&&rules[course])expiry=addYears(date,rules[course].years);if(!noExpiry&&!expiry)return alert("Expiry required unless No Expiry is selected.");activeSession={course,date,expiry,noExpiry,provider:document.getElementById("sessProvider").value.trim()||"N.A.",machines:splitCsv(document.getElementById("sessMachines").value),highRisk:splitCsv(document.getElementById("sessHighRisk").value),sessionEvidenceLink:document.getElementById("sessEvidenceLink").value.trim()||"",remarks:document.getElementById("sessRemarks").value.trim()||"Mass training attendance captured.",attendees:[],updatedAt:Date.now()};await setDoc(doc(db,"system","activeSession"),activeSession);renderActiveSession();renderAttendance();alert("Active session created.");}
function renderActiveSession(){const box=document.getElementById("activeSessionBox");if(!box)return;box.innerHTML=activeSession?`<div class="sessionBox"><b>${esc(activeSession.course)}</b><br><span class="small">${fmt(activeSession.date)} · Expiry: ${fmt(activeSession.expiry)} · ${activeSession.attendees?.length||0} attendees</span></div>`:"<p>No active session.</p>";}
async function addManualAttendance(){const id=upper(document.getElementById("scanId").value);await addAttendance(id);document.getElementById("scanId").value="";}
async function addAttendance(raw){if(!activeSession)return alert("Create session first.");const id=parseStaffId(raw),s=staffById(id);if(!s)return alert("Staff not found: "+id);if(activeSession.attendees?.some(a=>a.staffId===id))return;activeSession.attendees=activeSession.attendees||[];activeSession.attendees.push({staffId:id,name:s.name,scannedAt:new Date().toISOString()});await setDoc(doc(db,"system","activeSession"),activeSession);renderActiveSession();renderAttendance();}
function parseStaffId(v){try{const u=new URL(String(v));return upper(u.searchParams.get("id")||u.searchParams.get("staffId")||v);}catch(e){return upper(String(v).replace(/^STAFF:/i,"").replace(/^ID:/i,""));}}
function renderAttendance(){const box=document.getElementById("attendanceList");if(!box)return;if(!activeSession){box.innerHTML="<p>No active attendance.</p>";return;}box.innerHTML=(activeSession.attendees||[]).map(a=>`<div class="rowCard"><div><b>${esc(a.name)}</b><br><span class="small">${esc(a.staffId)} · ${new Date(a.scannedAt).toLocaleString("en-SG")}</span></div><button onclick="removeAttendee('${a.staffId}')">Remove</button></div>`).join("")||"<p>No attendees.</p>";}
window.removeAttendee=async function(id){activeSession.attendees=(activeSession.attendees||[]).filter(a=>a.staffId!==id);await setDoc(doc(db,"system","activeSession"),activeSession);renderAttendance();renderActiveSession();}
async function clearAttendance(){if(!activeSession)return;activeSession.attendees=[];await setDoc(doc(db,"system","activeSession"),activeSession);renderAttendance();renderActiveSession();}
async function finalizeSession(){if(!activeSession||!activeSession.attendees?.length)return alert("No attendees.");if(!confirm(`Create training records for ${activeSession.attendees.length} attendees?`))return;const sessionRef=await addDoc(collection(db,"sessions"),{...activeSession,finalizedAt:serverTimestamp()});for(const [i,a] of activeSession.attendees.entries()){await addDoc(collection(db,"training"),{staffId:a.staffId,course:activeSession.course,provider:activeSession.provider,certNo:`SESSION-${sessionRef.id.slice(0,6).toUpperCase()}-${String(i+1).padStart(3,"0")}`,attended:activeSession.date,expiry:activeSession.expiry,noExpiry:activeSession.noExpiry||false,machines:activeSession.machines||[],highRisk:activeSession.highRisk||[],remarks:activeSession.remarks,certLink:"",cardLink:"",sessionEvidenceLink:activeSession.sessionEvidenceLink||"",sourceSessionId:sessionRef.id,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}await setDoc(doc(db,"system","activeSession"),{});activeSession=null;await reloadAll();alert("Session finalized and training records created.");}
function startScanner(){if(!activeSession)return alert("Create session first.");if(scanner)return;scanner=new Html5Qrcode("qr-reader");scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:250}},async text=>await addAttendance(text)).catch(e=>alert("Camera scanner failed: "+e.message));}
function stopScanner(){if(scanner){scanner.stop().then(()=>{scanner.clear();scanner=null;});}}

function renderCerts(){const certSession=document.getElementById("certSession"),evidenceSession=document.getElementById("evidenceSession");if(!certSession||!evidenceSession)return;const opts=`<option value="">Select session</option>`+sessions.map(s=>`<option value="${s.id}">${esc(s.course)} - ${fmt(s.date)}</option>`).join("");certSession.innerHTML=opts;evidenceSession.innerHTML=opts;renderCertRecords();document.getElementById("certStatus").innerHTML=sessions.map(s=>{const recs=training.filter(t=>t.sourceSessionId===s.id),individual=recs.filter(t=>getCertUrl(t)||getCardUrl(t)).length,pending=recs.filter(t=>!getCertUrl(t)&&!getCardUrl(t)&&!getSessionEvidenceUrl(t)).length;return`<div class="record"><h3>${esc(s.course)} <span class="badge neutral">${fmt(s.date)}</span></h3><p>${recs.length} records · Individual evidence: ${individual}/${recs.length} · Pending evidence: ${pending}</p>${s.sessionEvidenceLink?`<button onclick="viewSessionEvidence('${s.id}')">View Session Evidence</button>`:"No session evidence"}</div>`}).join("")||"<p>No finalized sessions.</p>";}
function renderCertRecords(){const sessionId=document.getElementById("certSession")?.value,select=document.getElementById("certRecord");if(!select)return;const recs=training.filter(t=>t.sourceSessionId===sessionId);select.innerHTML=recs.map(t=>`<option value="${t.id}">${esc(t.staffId)} - ${esc(staffById(t.staffId)?.name||"")} (${getCertUrl(t)?"Cert linked":getSessionEvidenceUrl(t)?"Session evidence":"Pending"})</option>`).join("");}
async function uploadIndividualEvidence(){const id=document.getElementById("certRecord").value,t=training.find(x=>x.id===id);if(!t)return alert("Select worker record.");const certLink=document.getElementById("indCertLink").value.trim(),cardLink=document.getElementById("indCardLink").value.trim();if(!certLink&&!cardLink)return alert("Paste certificate or card link.");await updateDoc(doc(db,"training",id),{certLink:certLink||t.certLink||"",cardLink:cardLink||t.cardLink||"",updatedAt:serverTimestamp()});document.getElementById("indCertLink").value="";document.getElementById("indCardLink").value="";await reloadAll();alert("Individual evidence link saved.");}
async function uploadSessionEvidence(){const sessionId=document.getElementById("evidenceSession").value;if(!sessionId)return alert("Select session.");const link=document.getElementById("sessionEvidenceLink").value.trim();if(!link)return alert("Paste session evidence link.");await updateDoc(doc(db,"sessions",sessionId),{sessionEvidenceLink:link,updatedAt:serverTimestamp()});const recs=training.filter(t=>t.sourceSessionId===sessionId);for(const t of recs)await updateDoc(doc(db,"training",t.id),{sessionEvidenceLink:link,updatedAt:serverTimestamp()});document.getElementById("sessionEvidenceLink").value="";await reloadAll();alert("Session evidence link saved and linked.");}
function viewSessionEvidence(id){const s=sessions.find(x=>x.id===id);if(s?.sessionEvidenceLink)viewUrl(s.sessionEvidenceLink,s.course+" Session Evidence");}

async function saveRule(){const course=document.getElementById("ruleCourse").value.trim(),type=document.getElementById("ruleType").value,years=type==="noexpiry"?0:Number(document.getElementById("ruleYears").value),note=document.getElementById("ruleNote").value.trim()||(type==="noexpiry"?"No periodic renewal required.":"Company / site validity rule.");if(!course)return alert("Course required.");if(type==="expiry"&&!years)return alert("Validity years required for expiry-based training.");await setDoc(doc(db,"rules",course),{course,type,years,note});document.getElementById("ruleCourse").value="";document.getElementById("ruleYears").value="";document.getElementById("ruleNote").value="";await reloadAll();}
async function deleteRule(course){await deleteDoc(doc(db,"rules",course));await reloadAll();}
function toggleRuleYears(){const type=document.getElementById("ruleType").value;document.getElementById("ruleYears").disabled=type==="noexpiry";if(type==="noexpiry")document.getElementById("ruleYears").value="";}
async function seedRules(){const defaults=[["Forklift Operator Refresher","expiry",3,"Company/client refresher cycle. Verify deployment requirement before forklift operation."],["Work at Height","expiry",2,"Refresher cycle commonly required by company/client for WAH deployment."],["Confined Space Entry","expiry",3,"Competency/refresher cycle. Subject to valid PTW, gas test and entry control."],["Hot Work Safety","expiry",3,"Company/site refresher cycle. Subject to hot work PTW."],["Lifting Supervisor","expiry",3,"Competency review cycle. Verify against project/client requirement."],["Rigger and Signalman","expiry",3,"Competency review cycle. Verify against project/client requirement."],["Site Induction","noexpiry",0,"One-time site induction record unless client requires refresher."],["Toolbox Meeting","noexpiry",0,"Attendance record only; no expiry date required."],["Internal Safety Briefing","noexpiry",0,"Internal awareness / briefing record; no expiry date required."],["SGSecure Awareness","noexpiry",0,"Awareness briefing record; no expiry date required unless company sets refresher."]];for(const [course,type,years,note] of defaults)await setDoc(doc(db,"rules",course),{course,type,years,note});await reloadAll();alert("Default rules loaded.");}
function renderRules(){document.getElementById("rulesTable").innerHTML=Object.entries(rules).map(([course,r])=>`<tr><td>${esc(course)}</td><td>${r.type==="noexpiry"?"No Expiry":"Has Expiry"}</td><td>${r.type==="noexpiry"?"N.A.":r.years}</td><td>${esc(r.note)}</td><td><button onclick="deleteRule('${esc(course)}')">Delete</button></td></tr>`).join("");}
function renderCourseOptions(){document.getElementById("courseList").innerHTML=Object.keys(rules).map(c=>`<option value="${esc(c)}"></option>`).join("");}

function renderMetrics(){document.getElementById("mStaff").textContent=staff.length;document.getElementById("mTraining").textContent=training.length;document.getElementById("mExpired").textContent=training.filter(t=>statusOf(t).label==="Expired").length;document.getElementById("mExpiring").textContent=training.filter(t=>statusOf(t).label==="Expiring Soon").length;document.getElementById("mNoExpiry").textContent=training.filter(t=>isNoExpiryRecord(t)).length;}
function renderReports(type="expired"){let rows=training;if(type==="expired")rows=rows.filter(t=>statusOf(t).label==="Expired");if(type==="expiring")rows=rows.filter(t=>statusOf(t).label==="Expiring Soon");if(type==="noexpiry")rows=rows.filter(t=>isNoExpiryRecord(t));if(type==="missingEvidence")rows=rows.filter(t=>!getCertUrl(t)&&!getSessionEvidenceUrl(t));document.getElementById("reportBox").innerHTML=`<table><thead><tr><th>Staff</th><th>Course</th><th>Status</th><th>Evidence</th><th>Audit Note</th></tr></thead><tbody>${rows.map(t=>{const s=staffById(t.staffId),st=statusOf(t);return`<tr><td>${esc(s?.name||"Unknown")}<br><span class="small">${esc(t.staffId)}</span></td><td>${esc(t.course)}</td><td><span class="badge ${st.cls}">${st.label}</span><br><span class="small">${fmt(t.expiry)}</span></td><td>${evidenceButtons(t)}</td><td>${isNoExpiryRecord(t)?"No expiry required / record retained for audit.":st.label==="Expired"?"Do not deploy until refreshed.":st.label==="Expiring Soon"?"Plan refresher before expiry.":"Valid."}</td></tr>`}).join("")||"<tr><td colspan='5'>No records.</td></tr>"}</tbody></table>`;}
function exportTrainingCSV(){const rows=[["Staff ID","Staff Name","Course","Provider","Cert No","Attended","Expiry","No Expiry","Status","Certificate Link","Card Link","Session Evidence Link","Remarks"]];training.forEach(t=>{const s=staffById(t.staffId),st=statusOf(t);rows.push([t.staffId,s?.name||"",t.course,t.provider,t.certNo,t.attended,fmt(t.expiry),isNoExpiryRecord(t)?"Yes":"No",st.label,getCertUrl(t),getCardUrl(t),getSessionEvidenceUrl(t),t.remarks]);});const csv=rows.map(r=>r.map(x=>`"${String(x??"").replace(/"/g,'""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="training-records-audit.csv";a.click();URL.revokeObjectURL(url);}
function renderQrCards(){const box=document.getElementById("qrCards");if(!box)return;box.innerHTML=staff.map(s=>`<div class="qrCard"><h3>${esc(s.name)}</h3><p>${esc(s.id)}</p><canvas id="qr-${esc(s.id)}"></canvas><p class="small">${esc(s.trade)}</p></div>`).join("");staff.forEach(s=>{const c=document.getElementById("qr-"+s.id);if(c&&window.QRCode)QRCode.toCanvas(c,`STAFF:${s.id}`,{width:140});});}
function viewUrl(url,title){document.getElementById("viewerTitle").textContent=title||"Evidence";document.getElementById("viewerBody").innerHTML=`<p><a href="${esc(url)}" target="_blank" rel="noopener">Open Evidence Link</a></p><iframe src="${esc(url)}" class="viewerFrame"></iframe>`;document.getElementById("viewer").showModal();}
function closeViewer(){document.getElementById("viewer").close();}
